/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.factestatal;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author comercial.gvca
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        
        this.setLocationRelativeTo(null);// Centrar la ventana        
        
        // Cambiar por la direccion donde se tiene la imagen de fondo que se quiera en el software
        Image img = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/fondo.jpg"));
        this.desktopPane.setImagen(img);        
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        contenedorToolBar = new javax.swing.JToolBar();
        importarExportarToolBar = new javax.swing.JToolBar();
        importarButton = new javax.swing.JButton();
        exportarButton = new javax.swing.JButton();
        accionesToolBar = new javax.swing.JToolBar();
        clientesButton = new javax.swing.JButton();
        serviciosXClientesButton = new javax.swing.JButton();
        facturarButton = new javax.swing.JButton();
        consultasAFacturasButton = new javax.swing.JButton();
        informesToolBar = new javax.swing.JToolBar();
        facturasButton = new javax.swing.JButton();
        cierreToolBar = new javax.swing.JToolBar();
        ficheroABancoButton = new javax.swing.JButton();
        cierreMesButton = new javax.swing.JButton();
        cobrosToolBar = new javax.swing.JToolBar();
        captarCobroButton = new javax.swing.JButton();
        desktopPane = new myclass.JDescktopPaneImage();
        usuarioToolBar = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        usuarioAutenticadoLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        verMenu = new javax.swing.JMenu();
        barraImportarExportarMenuItem = new javax.swing.JCheckBoxMenuItem();
        barraAccionesMenuItem = new javax.swing.JCheckBoxMenuItem();
        barraInformesMenuItem = new javax.swing.JCheckBoxMenuItem();
        barraCierreMesMenuItem = new javax.swing.JCheckBoxMenuItem();
        barraCobrosMenuItem = new javax.swing.JCheckBoxMenuItem();
        ficherosMenu = new javax.swing.JMenu();
        datosEmpresaMenuItem = new javax.swing.JMenuItem();
        tipoServiciosMenuItem = new javax.swing.JMenuItem();
        serviciosMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        titularesMenuItem = new javax.swing.JMenuItem();
        clientesMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        detallesControlMenuItem = new javax.swing.JMenuItem();
        produccionMenu = new javax.swing.JMenu();
        relacionSMMenuItem = new javax.swing.JMenuItem();
        servicioInclAlcMenuItem = new javax.swing.JMenuItem();
        servicioXclienteMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        facturacionMenuItem = new javax.swing.JMenuItem();
        consultasAfacturasMenuItem = new javax.swing.JMenuItem();
        informesMenu = new javax.swing.JMenu();
        listadoFacturasMenuItem = new javax.swing.JMenuItem();
        facturasMenuItem = new javax.swing.JMenuItem();
        facturasRechazadasMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        listadoTitularesClientesMenuItem = new javax.swing.JMenuItem();
        mesYAcomuladoFacturasMenu = new javax.swing.JMenu();
        enCUPMenuItem = new javax.swing.JMenuItem();
        enCUCMenuItem = new javax.swing.JMenuItem();
        totalFacturadoPresupuestadoMenuItem = new javax.swing.JMenuItem();
        listadoGrandesConsumidoresMenuItem = new javax.swing.JMenuItem();
        listadoPorSectoresMenuItem = new javax.swing.JMenuItem();
        informeMetrosMenu = new javax.swing.JMenu();
        informeMetrosCUPMenuItem = new javax.swing.JMenuItem();
        informeMetrosCUCMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        comprobanteOperacionnesMenuItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        clientesSinFacturarMenu = new javax.swing.JMenu();
        clientesSinFacturarCUPMenuItem = new javax.swing.JMenuItem();
        clientesSinFacturarCUCMenuItem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        historicoMenu = new javax.swing.JMenu();
        historicoDeFacturasMenuItem = new javax.swing.JMenuItem();
        datosCierreMenu = new javax.swing.JMenu();
        crearFicheroBancoMenuItem = new javax.swing.JMenuItem();
        consultarFcheroBancoMenuItem = new javax.swing.JMenuItem();
        copiarDispositivoSalidaMenuItem = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        copiarFicheroVieneBancoMenuItem = new javax.swing.JMenuItem();
        consultarFicheroVieneBancoMenuItem = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        cierreMesMenuItem = new javax.swing.JMenuItem();
        cobrosMenu = new javax.swing.JMenu();
        capturarFacturasXCobroMenuItem = new javax.swing.JMenuItem();
        consultaFacturasXCobroMenuItem = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        cobrosAFacturasMenuItem = new javax.swing.JMenuItem();
        consultasACobrosFacturasMenuItem = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        registroCobrosMenuItem = new javax.swing.JMenuItem();
        reporteEdadesMenuItem = new javax.swing.JMenuItem();
        herramientasMenu = new javax.swing.JMenu();
        usersMenuItem = new javax.swing.JMenuItem();
        cambiarContrasennaMenuItem = new javax.swing.JMenuItem();
        prodMenu = new javax.swing.JMenu();
        ayudaMunu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GEDSAA");
        setIconImage(getIconImage());

        contenedorToolBar.setFloatable(false);
        contenedorToolBar.setRollover(true);

        importarExportarToolBar.setRollover(true);
        importarExportarToolBar.setName("Imporar - Exportar"); // NOI18N

        importarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/importar.png"))); // NOI18N
        importarButton.setToolTipText("Importar");
        importarButton.setFocusable(false);
        importarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importarExportarToolBar.add(importarButton);

        exportarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/exportar.png"))); // NOI18N
        exportarButton.setToolTipText("Exportar");
        exportarButton.setFocusable(false);
        exportarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importarExportarToolBar.add(exportarButton);

        contenedorToolBar.add(importarExportarToolBar);

        accionesToolBar.setRollover(true);
        accionesToolBar.setName("Acciones"); // NOI18N

        clientesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/clientes.png"))); // NOI18N
        clientesButton.setToolTipText("Clientes");
        clientesButton.setFocusable(false);
        clientesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        accionesToolBar.add(clientesButton);

        serviciosXClientesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/serviciosXcliantes.png"))); // NOI18N
        serviciosXClientesButton.setToolTipText("Servicios por Clientes");
        serviciosXClientesButton.setFocusable(false);
        serviciosXClientesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        serviciosXClientesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        accionesToolBar.add(serviciosXClientesButton);

        facturarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/facturar.png"))); // NOI18N
        facturarButton.setToolTipText("Facturar");
        facturarButton.setFocusable(false);
        facturarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        facturarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        accionesToolBar.add(facturarButton);

        consultasAFacturasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/consultar_facturas.png"))); // NOI18N
        consultasAFacturasButton.setToolTipText("Consultas a Facturas");
        consultasAFacturasButton.setFocusable(false);
        consultasAFacturasButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultasAFacturasButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        accionesToolBar.add(consultasAFacturasButton);

        contenedorToolBar.add(accionesToolBar);

        informesToolBar.setRollover(true);
        informesToolBar.setName("Informes"); // NOI18N

        facturasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/facturas.png"))); // NOI18N
        facturasButton.setToolTipText("Facturas");
        facturasButton.setFocusable(false);
        facturasButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        facturasButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        informesToolBar.add(facturasButton);

        contenedorToolBar.add(informesToolBar);

        cierreToolBar.setRollover(true);
        cierreToolBar.setName("Cierre de mes"); // NOI18N

        ficheroABancoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/fichero_a_banco.png"))); // NOI18N
        ficheroABancoButton.setToolTipText("Fichero que va al Banco");
        ficheroABancoButton.setFocusable(false);
        ficheroABancoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ficheroABancoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cierreToolBar.add(ficheroABancoButton);

        cierreMesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/cierre_mes.png"))); // NOI18N
        cierreMesButton.setToolTipText("Cerrar Mes");
        cierreMesButton.setFocusable(false);
        cierreMesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cierreMesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cierreToolBar.add(cierreMesButton);

        contenedorToolBar.add(cierreToolBar);

        cobrosToolBar.setRollover(true);
        cobrosToolBar.setName("Cobros"); // NOI18N

        captarCobroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/capturar_facturas_cobros.png"))); // NOI18N
        captarCobroButton.setToolTipText("Captar Factura x Cobro");
        captarCobroButton.setFocusable(false);
        captarCobroButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        captarCobroButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cobrosToolBar.add(captarCobroButton);

        contenedorToolBar.add(cobrosToolBar);

        usuarioToolBar.setFloatable(false);
        usuarioToolBar.setRollover(true);

        jLabel1.setText("Usuario Autenticado:");
        usuarioToolBar.add(jLabel1);

        usuarioAutenticadoLabel.setText(" User Name");
        usuarioToolBar.add(usuarioAutenticadoLabel);

        fileMenu.setMnemonic('a');
        fileMenu.setText("Archivo");

        importMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        importMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/importar.png"))); // NOI18N
        importMenuItem.setText("Importar");
        fileMenu.add(importMenuItem);

        exportMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exportMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/exportar.png"))); // NOI18N
        exportMenuItem.setText("Exportar");
        fileMenu.add(exportMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Salir");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        verMenu.setText("Ver");

        barraImportarExportarMenuItem.setSelected(true);
        barraImportarExportarMenuItem.setText("Mostrar Barra Importar Exportar");
        verMenu.add(barraImportarExportarMenuItem);

        barraAccionesMenuItem.setSelected(true);
        barraAccionesMenuItem.setText("Mostrar Barra Acciones");
        verMenu.add(barraAccionesMenuItem);

        barraInformesMenuItem.setSelected(true);
        barraInformesMenuItem.setText("Mostrar Barra Informes");
        verMenu.add(barraInformesMenuItem);

        barraCierreMesMenuItem.setSelected(true);
        barraCierreMesMenuItem.setText("Mostrar Barra Cierre de Mes");
        verMenu.add(barraCierreMesMenuItem);

        barraCobrosMenuItem.setSelected(true);
        barraCobrosMenuItem.setText("Mostrar Barra Cobros");
        verMenu.add(barraCobrosMenuItem);

        menuBar.add(verMenu);

        ficherosMenu.setMnemonic('f');
        ficherosMenu.setText("Ficheros");

        datosEmpresaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        datosEmpresaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/datos_empresa.png"))); // NOI18N
        datosEmpresaMenuItem.setText("Datos de la Empresa");
        ficherosMenu.add(datosEmpresaMenuItem);

        tipoServiciosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        tipoServiciosMenuItem.setText("Tipos de Servicios");
        ficherosMenu.add(tipoServiciosMenuItem);

        serviciosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        serviciosMenuItem.setText("Servicios");
        ficherosMenu.add(serviciosMenuItem);
        ficherosMenu.add(jSeparator1);

        titularesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        titularesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/titulares.png"))); // NOI18N
        titularesMenuItem.setText("Titulares");
        ficherosMenu.add(titularesMenuItem);

        clientesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        clientesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/clientes.png"))); // NOI18N
        clientesMenuItem.setText("Clientes");
        ficherosMenu.add(clientesMenuItem);
        ficherosMenu.add(jSeparator2);

        detallesControlMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        detallesControlMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/detalles_control.png"))); // NOI18N
        detallesControlMenuItem.setText("Detalles de Control");
        ficherosMenu.add(detallesControlMenuItem);

        menuBar.add(ficherosMenu);

        produccionMenu.setMnemonic('p');
        produccionMenu.setText("Producción");

        relacionSMMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/relacion_servicio_sobreconsumo.png"))); // NOI18N
        relacionSMMenuItem.setText("Relación de Servicio Metrado - Sobreconsumo");
        produccionMenu.add(relacionSMMenuItem);

        servicioInclAlcMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/servicios_alcantarillado.png"))); // NOI18N
        servicioInclAlcMenuItem.setText("Servicios que incluyen Alcantatrillado");
        produccionMenu.add(servicioInclAlcMenuItem);

        servicioXclienteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/serviciosXcliantes.png"))); // NOI18N
        servicioXclienteMenuItem.setText("Servicios por clientes");
        produccionMenu.add(servicioXclienteMenuItem);
        produccionMenu.add(jSeparator3);

        facturacionMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/facturar.png"))); // NOI18N
        facturacionMenuItem.setText("Facturar");
        produccionMenu.add(facturacionMenuItem);

        consultasAfacturasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/consultar_facturas.png"))); // NOI18N
        consultasAfacturasMenuItem.setText("Consultas a Facturas");
        produccionMenu.add(consultasAfacturasMenuItem);

        menuBar.add(produccionMenu);

        informesMenu.setMnemonic('i');
        informesMenu.setText("Informes");

        listadoFacturasMenuItem.setText("Listado de Facturas");
        informesMenu.add(listadoFacturasMenuItem);

        facturasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/facturas.png"))); // NOI18N
        facturasMenuItem.setText("Facturas");
        informesMenu.add(facturasMenuItem);

        facturasRechazadasMenuItem.setText("Facturas Rechazadas");
        informesMenu.add(facturasRechazadasMenuItem);
        informesMenu.add(jSeparator4);

        listadoTitularesClientesMenuItem.setText("Listado de Titulares y Clientes");
        informesMenu.add(listadoTitularesClientesMenuItem);

        mesYAcomuladoFacturasMenu.setText("Mes y Acomulado de Facturas");

        enCUPMenuItem.setText("En CUP");
        mesYAcomuladoFacturasMenu.add(enCUPMenuItem);

        enCUCMenuItem.setText("En CUC");
        mesYAcomuladoFacturasMenu.add(enCUCMenuItem);

        informesMenu.add(mesYAcomuladoFacturasMenu);

        totalFacturadoPresupuestadoMenuItem.setText("Total Facturado Presupuestado");
        informesMenu.add(totalFacturadoPresupuestadoMenuItem);

        listadoGrandesConsumidoresMenuItem.setText("Listado de Grandes Consumidores");
        informesMenu.add(listadoGrandesConsumidoresMenuItem);

        listadoPorSectoresMenuItem.setText("Listado por Sector");
        informesMenu.add(listadoPorSectoresMenuItem);

        informeMetrosMenu.setText("Informe Metros");

        informeMetrosCUPMenuItem.setText("Informe de Metros en CUP");
        informeMetrosMenu.add(informeMetrosCUPMenuItem);

        informeMetrosCUCMenuItem.setText("Informe de Metros en CUC");
        informeMetrosMenu.add(informeMetrosCUCMenuItem);

        informesMenu.add(informeMetrosMenu);
        informesMenu.add(jSeparator5);

        comprobanteOperacionnesMenuItem.setText("Comprobantes de Operaciones");
        informesMenu.add(comprobanteOperacionnesMenuItem);
        informesMenu.add(jSeparator6);

        clientesSinFacturarMenu.setText("Clientes sin Facturar");

        clientesSinFacturarCUPMenuItem.setText("Clientes sin Facturar en CUP");
        clientesSinFacturarMenu.add(clientesSinFacturarCUPMenuItem);

        clientesSinFacturarCUCMenuItem.setText("Clientes sin Facturar en CUC");
        clientesSinFacturarMenu.add(clientesSinFacturarCUCMenuItem);

        informesMenu.add(clientesSinFacturarMenu);
        informesMenu.add(jSeparator7);

        historicoMenu.setText("Historico");

        historicoDeFacturasMenuItem.setText("Historicos de las Facturas");
        historicoMenu.add(historicoDeFacturasMenuItem);

        informesMenu.add(historicoMenu);

        menuBar.add(informesMenu);

        datosCierreMenu.setMnemonic('d');
        datosCierreMenu.setText("Datos de Cierre");

        crearFicheroBancoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/fichero_a_banco.png"))); // NOI18N
        crearFicheroBancoMenuItem.setText("Crear fichero que va al Banco");
        datosCierreMenu.add(crearFicheroBancoMenuItem);

        consultarFcheroBancoMenuItem.setText("Consultar el fichero que va al Banco");
        datosCierreMenu.add(consultarFcheroBancoMenuItem);

        copiarDispositivoSalidaMenuItem.setText("Copiar al dispositivo de salida para enviar al Banco");
        datosCierreMenu.add(copiarDispositivoSalidaMenuItem);
        datosCierreMenu.add(jSeparator8);

        copiarFicheroVieneBancoMenuItem.setText("Copiar fichero que viene del Banco");
        datosCierreMenu.add(copiarFicheroVieneBancoMenuItem);

        consultarFicheroVieneBancoMenuItem.setText("Consultar fichero que viene del Banco");
        datosCierreMenu.add(consultarFicheroVieneBancoMenuItem);
        datosCierreMenu.add(jSeparator9);

        cierreMesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/cierre_mes.png"))); // NOI18N
        cierreMesMenuItem.setText("Cierre de Mes");
        datosCierreMenu.add(cierreMesMenuItem);

        menuBar.add(datosCierreMenu);

        cobrosMenu.setMnemonic('c');
        cobrosMenu.setText("Cobros");

        capturarFacturasXCobroMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/capturar_facturas_cobros.png"))); // NOI18N
        capturarFacturasXCobroMenuItem.setText("Captar Facturas x Cobro");
        cobrosMenu.add(capturarFacturasXCobroMenuItem);

        consultaFacturasXCobroMenuItem.setText("Consulta de Facturas x Cobro");
        cobrosMenu.add(consultaFacturasXCobroMenuItem);
        cobrosMenu.add(jSeparator11);

        cobrosAFacturasMenuItem.setText("Cobros a Facturas");
        cobrosMenu.add(cobrosAFacturasMenuItem);

        consultasACobrosFacturasMenuItem.setText("Consultas a Cobros de Facturas");
        cobrosMenu.add(consultasACobrosFacturasMenuItem);
        cobrosMenu.add(jSeparator10);

        registroCobrosMenuItem.setText("Registro de Cobros");
        cobrosMenu.add(registroCobrosMenuItem);

        reporteEdadesMenuItem.setText("Reporte de Edades");
        cobrosMenu.add(reporteEdadesMenuItem);

        menuBar.add(cobrosMenu);

        herramientasMenu.setMnemonic('e');
        herramientasMenu.setText("Herramientas");

        usersMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/usuarios.png"))); // NOI18N
        usersMenuItem.setMnemonic('d');
        usersMenuItem.setText("Usuarios");
        herramientasMenu.add(usersMenuItem);

        cambiarContrasennaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/password.png"))); // NOI18N
        cambiarContrasennaMenuItem.setText("Cambiar Contraseña");
        herramientasMenu.add(cambiarContrasennaMenuItem);

        menuBar.add(herramientasMenu);

        prodMenu.setMnemonic('r');
        prodMenu.setText("Productividad");
        menuBar.add(prodMenu);

        ayudaMunu.setMnemonic('h');
        ayudaMunu.setText("Ayuda");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contenido");
        ayudaMunu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sobre Nosotros");
        ayudaMunu.add(aboutMenuItem);

        menuBar.add(ayudaMunu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuarioToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contenedorToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem aboutMenuItem;
    public javax.swing.JToolBar accionesToolBar;
    private javax.swing.JMenu ayudaMunu;
    public javax.swing.JCheckBoxMenuItem barraAccionesMenuItem;
    public javax.swing.JCheckBoxMenuItem barraCierreMesMenuItem;
    public javax.swing.JCheckBoxMenuItem barraCobrosMenuItem;
    public javax.swing.JCheckBoxMenuItem barraImportarExportarMenuItem;
    public javax.swing.JCheckBoxMenuItem barraInformesMenuItem;
    public javax.swing.JMenuItem cambiarContrasennaMenuItem;
    public javax.swing.JButton captarCobroButton;
    public javax.swing.JMenuItem capturarFacturasXCobroMenuItem;
    public javax.swing.JButton cierreMesButton;
    public javax.swing.JMenuItem cierreMesMenuItem;
    public javax.swing.JToolBar cierreToolBar;
    public javax.swing.JButton clientesButton;
    public javax.swing.JMenuItem clientesMenuItem;
    public javax.swing.JMenuItem clientesSinFacturarCUCMenuItem;
    public javax.swing.JMenuItem clientesSinFacturarCUPMenuItem;
    private javax.swing.JMenu clientesSinFacturarMenu;
    public javax.swing.JMenuItem cobrosAFacturasMenuItem;
    private javax.swing.JMenu cobrosMenu;
    public javax.swing.JToolBar cobrosToolBar;
    public javax.swing.JMenuItem comprobanteOperacionnesMenuItem;
    public javax.swing.JMenuItem consultaFacturasXCobroMenuItem;
    public javax.swing.JMenuItem consultarFcheroBancoMenuItem;
    public javax.swing.JMenuItem consultarFicheroVieneBancoMenuItem;
    public javax.swing.JMenuItem consultasACobrosFacturasMenuItem;
    public javax.swing.JButton consultasAFacturasButton;
    public javax.swing.JMenuItem consultasAfacturasMenuItem;
    private javax.swing.JToolBar contenedorToolBar;
    public javax.swing.JMenuItem contentMenuItem;
    public javax.swing.JMenuItem copiarDispositivoSalidaMenuItem;
    public javax.swing.JMenuItem copiarFicheroVieneBancoMenuItem;
    public javax.swing.JMenuItem crearFicheroBancoMenuItem;
    private javax.swing.JMenu datosCierreMenu;
    public javax.swing.JMenuItem datosEmpresaMenuItem;
    public myclass.JDescktopPaneImage desktopPane;
    public javax.swing.JMenuItem detallesControlMenuItem;
    public javax.swing.JMenuItem enCUCMenuItem;
    public javax.swing.JMenuItem enCUPMenuItem;
    public javax.swing.JMenuItem exitMenuItem;
    public javax.swing.JMenuItem exportMenuItem;
    public javax.swing.JButton exportarButton;
    public javax.swing.JMenuItem facturacionMenuItem;
    public javax.swing.JButton facturarButton;
    public javax.swing.JButton facturasButton;
    public javax.swing.JMenuItem facturasMenuItem;
    public javax.swing.JMenuItem facturasRechazadasMenuItem;
    public javax.swing.JButton ficheroABancoButton;
    private javax.swing.JMenu ficherosMenu;
    private javax.swing.JMenu fileMenu;
    public javax.swing.JMenu herramientasMenu;
    public javax.swing.JMenuItem historicoDeFacturasMenuItem;
    private javax.swing.JMenu historicoMenu;
    public javax.swing.JMenuItem importMenuItem;
    public javax.swing.JButton importarButton;
    public javax.swing.JToolBar importarExportarToolBar;
    public javax.swing.JMenuItem informeMetrosCUCMenuItem;
    public javax.swing.JMenuItem informeMetrosCUPMenuItem;
    private javax.swing.JMenu informeMetrosMenu;
    private javax.swing.JMenu informesMenu;
    public javax.swing.JToolBar informesToolBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    public javax.swing.JMenuItem listadoFacturasMenuItem;
    public javax.swing.JMenuItem listadoGrandesConsumidoresMenuItem;
    public javax.swing.JMenuItem listadoPorSectoresMenuItem;
    public javax.swing.JMenuItem listadoTitularesClientesMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mesYAcomuladoFacturasMenu;
    private javax.swing.JMenu prodMenu;
    private javax.swing.JMenu produccionMenu;
    public javax.swing.JMenuItem registroCobrosMenuItem;
    public javax.swing.JMenuItem relacionSMMenuItem;
    public javax.swing.JMenuItem reporteEdadesMenuItem;
    public javax.swing.JMenuItem servicioInclAlcMenuItem;
    public javax.swing.JMenuItem servicioXclienteMenuItem;
    public javax.swing.JMenuItem serviciosMenuItem;
    public javax.swing.JButton serviciosXClientesButton;
    public javax.swing.JMenuItem tipoServiciosMenuItem;
    public javax.swing.JMenuItem titularesMenuItem;
    public javax.swing.JMenuItem totalFacturadoPresupuestadoMenuItem;
    public javax.swing.JMenuItem usersMenuItem;
    public javax.swing.JLabel usuarioAutenticadoLabel;
    private javax.swing.JToolBar usuarioToolBar;
    private javax.swing.JMenu verMenu;
    // End of variables declaration//GEN-END:variables

}
