/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views.factestatal.ficheros;

/**
 *
 * @author Carlos
 */
public class cambiarPassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form cambiarPassword
     */
    public cambiarPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contrasennaActualLabel = new javax.swing.JLabel();
        nuevaContrasennaLabel = new javax.swing.JLabel();
        repetirContrasennaNuevaLabel = new javax.swing.JLabel();
        contrasennaActualPasswordField = new javax.swing.JPasswordField();
        nuevaContrasennaPasswordField = new javax.swing.JPasswordField();
        repetirContrasennaNuevaPasswordField = new javax.swing.JPasswordField();
        cambiarContrasennaButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cambiar contraseña");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/password.png"))); // NOI18N

        contrasennaActualLabel.setText("Constraseña actual:");

        nuevaContrasennaLabel.setText("Nueva contraseña:");

        repetirContrasennaNuevaLabel.setText("Repetir nueva contraseña:");

        cambiarContrasennaButton.setText("Cambiar contraseña");

        cancelarButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cambiarContrasennaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(repetirContrasennaNuevaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(repetirContrasennaNuevaPasswordField))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contrasennaActualLabel)
                                .addComponent(nuevaContrasennaLabel))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(contrasennaActualPasswordField)
                                .addComponent(nuevaContrasennaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasennaActualLabel)
                    .addComponent(contrasennaActualPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaContrasennaLabel)
                    .addComponent(nuevaContrasennaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repetirContrasennaNuevaLabel)
                    .addComponent(repetirContrasennaNuevaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarContrasennaButton)
                    .addComponent(cancelarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarContrasennaButton;
    public javax.swing.JButton cancelarButton;
    private javax.swing.JLabel contrasennaActualLabel;
    public javax.swing.JPasswordField contrasennaActualPasswordField;
    private javax.swing.JLabel nuevaContrasennaLabel;
    public javax.swing.JPasswordField nuevaContrasennaPasswordField;
    private javax.swing.JLabel repetirContrasennaNuevaLabel;
    public javax.swing.JPasswordField repetirContrasennaNuevaPasswordField;
    // End of variables declaration//GEN-END:variables
}
