/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package factestatal.ficheros;

/**
 *
 * @author comercial.gvca
 */
public class Servicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Servicios
     */
    public Servicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visualizarSeviciosPanel = new javax.swing.JPanel();
        visualizarServiciosScrollPane = new javax.swing.JScrollPane();
        visualizarServiciosTable = new javax.swing.JTable();
        agregarModificarPanel = new javax.swing.JPanel();
        datosServiciosFacturadosLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        descripcionTextField = new javax.swing.JTextField();
        unidadMedidaLabel = new javax.swing.JLabel();
        unidadMedidaTextField = new javax.swing.JTextField();
        tipoServicioLabel = new javax.swing.JLabel();
        tipoServicioComboBox = new javax.swing.JComboBox();
        preciosPanel = new javax.swing.JPanel();
        cucLabel = new javax.swing.JLabel();
        cucTextField = new javax.swing.JTextField();
        cupLabel = new javax.swing.JLabel();
        cupTextField = new javax.swing.JTextField();
        agregarModificarButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Servicios");

        visualizarSeviciosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualizar Servicios"));

        visualizarServiciosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Unidad de Medida", "Tipo de Servicio", "Precio CUC", "Precio CUP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        visualizarServiciosScrollPane.setViewportView(visualizarServiciosTable);

        javax.swing.GroupLayout visualizarSeviciosPanelLayout = new javax.swing.GroupLayout(visualizarSeviciosPanel);
        visualizarSeviciosPanel.setLayout(visualizarSeviciosPanelLayout);
        visualizarSeviciosPanelLayout.setHorizontalGroup(
            visualizarSeviciosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarSeviciosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visualizarServiciosScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        visualizarSeviciosPanelLayout.setVerticalGroup(
            visualizarSeviciosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visualizarSeviciosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visualizarServiciosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );

        agregarModificarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar/ Modificar"));

        datosServiciosFacturadosLabel.setText("Datos de los servicios que se facturan");

        descripcionLabel.setText("Descripción:");

        descripcionTextField.setToolTipText("Entre la descripción del Servicio");

        unidadMedidaLabel.setText("Unidad de Medida:");

        unidadMedidaTextField.setToolTipText("Unidad de medida");

        tipoServicioLabel.setText("Tipo de Servicio:");

        tipoServicioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoServicioComboBox.setToolTipText("Tipo de Servicio");

        preciosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Precios"));

        cucLabel.setText("CUC");

        cucTextField.setToolTipText("Precio en cuc");

        cupLabel.setText("CUP");

        cupTextField.setToolTipText("Precio en cup");

        javax.swing.GroupLayout preciosPanelLayout = new javax.swing.GroupLayout(preciosPanel);
        preciosPanel.setLayout(preciosPanelLayout);
        preciosPanelLayout.setHorizontalGroup(
            preciosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preciosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cucLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cupLabel)
                .addContainerGap())
            .addGroup(preciosPanelLayout.createSequentialGroup()
                .addComponent(cucTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        preciosPanelLayout.setVerticalGroup(
            preciosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preciosPanelLayout.createSequentialGroup()
                .addGroup(preciosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cucLabel)
                    .addComponent(cupLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(preciosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cucTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        agregarModificarButton.setText("Agregar/ Modificar");
        agregarModificarButton.setToolTipText("Click para agregar o modificar un Servicio");

        javax.swing.GroupLayout agregarModificarPanelLayout = new javax.swing.GroupLayout(agregarModificarPanel);
        agregarModificarPanel.setLayout(agregarModificarPanelLayout);
        agregarModificarPanelLayout.setHorizontalGroup(
            agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarModificarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarModificarPanelLayout.createSequentialGroup()
                        .addComponent(descripcionLabel)
                        .addGap(35, 35, 35)
                        .addComponent(descripcionTextField))
                    .addGroup(agregarModificarPanelLayout.createSequentialGroup()
                        .addComponent(tipoServicioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoServicioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(agregarModificarPanelLayout.createSequentialGroup()
                        .addGroup(agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datosServiciosFacturadosLabel)
                            .addComponent(preciosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addGroup(agregarModificarPanelLayout.createSequentialGroup()
                        .addComponent(unidadMedidaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadMedidaTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarModificarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarModificarButton)))
                .addContainerGap())
        );
        agregarModificarPanelLayout.setVerticalGroup(
            agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarModificarPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(datosServiciosFacturadosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionLabel)
                    .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadMedidaLabel)
                    .addComponent(unidadMedidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarModificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoServicioLabel)
                    .addComponent(tipoServicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preciosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarModificarButton)
                .addContainerGap())
        );

        modificarButton.setText("Modificar");

        eliminarButton.setText("Eliminar");
        eliminarButton.setToolTipText("Click para eliminar un servicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(agregarModificarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(visualizarSeviciosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(visualizarSeviciosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarModificarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modificarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarModificarButton;
    private javax.swing.JPanel agregarModificarPanel;
    private javax.swing.JLabel cucLabel;
    public javax.swing.JTextField cucTextField;
    private javax.swing.JLabel cupLabel;
    public javax.swing.JTextField cupTextField;
    private javax.swing.JLabel datosServiciosFacturadosLabel;
    private javax.swing.JLabel descripcionLabel;
    public javax.swing.JTextField descripcionTextField;
    public javax.swing.JButton eliminarButton;
    public javax.swing.JButton modificarButton;
    private javax.swing.JPanel preciosPanel;
    public javax.swing.JComboBox tipoServicioComboBox;
    private javax.swing.JLabel tipoServicioLabel;
    private javax.swing.JLabel unidadMedidaLabel;
    public javax.swing.JTextField unidadMedidaTextField;
    private javax.swing.JScrollPane visualizarServiciosScrollPane;
    public javax.swing.JTable visualizarServiciosTable;
    private javax.swing.JPanel visualizarSeviciosPanel;
    // End of variables declaration//GEN-END:variables
}
