/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package factestatal.ficheros;

/**
 *
 * @author comercial.gvca
 */
public class TipoServicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TipoServicios
     */
    public TipoServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarTipoServicioPanel = new javax.swing.JPanel();
        tipoServicioLabel = new javax.swing.JLabel();
        tipoServicioTextField = new javax.swing.JTextField();
        agregarModificarButton = new javax.swing.JButton();
        modificarEliminarPanel = new javax.swing.JPanel();
        modificarEliminarScrollPane = new javax.swing.JScrollPane();
        modificarEliminarList = new javax.swing.JList();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tipo de Servicios");

        agregarTipoServicioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar tipo de servicios"));

        tipoServicioLabel.setText("Tipos de Servicios:");

        tipoServicioTextField.setToolTipText("Entre el Tipo de Servicio, Metrado, Tarifado, etc.");

        agregarModificarButton.setText("Agregar/ Modificar");

        javax.swing.GroupLayout agregarTipoServicioPanelLayout = new javax.swing.GroupLayout(agregarTipoServicioPanel);
        agregarTipoServicioPanel.setLayout(agregarTipoServicioPanelLayout);
        agregarTipoServicioPanelLayout.setHorizontalGroup(
            agregarTipoServicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarTipoServicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarTipoServicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarTipoServicioPanelLayout.createSequentialGroup()
                        .addComponent(tipoServicioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoServicioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarTipoServicioPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarModificarButton)))
                .addContainerGap())
        );
        agregarTipoServicioPanelLayout.setVerticalGroup(
            agregarTipoServicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarTipoServicioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(agregarTipoServicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoServicioLabel)
                    .addComponent(tipoServicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(agregarModificarButton))
        );

        modificarEliminarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar/ Eliminar"));

        modificarEliminarList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        modificarEliminarList.setToolTipText("Escoja un Servicio a Modificar o Eliminar");
        modificarEliminarScrollPane.setViewportView(modificarEliminarList);

        eliminarButton.setText("Eliminar");

        javax.swing.GroupLayout modificarEliminarPanelLayout = new javax.swing.GroupLayout(modificarEliminarPanel);
        modificarEliminarPanel.setLayout(modificarEliminarPanelLayout);
        modificarEliminarPanelLayout.setHorizontalGroup(
            modificarEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarEliminarPanelLayout.createSequentialGroup()
                .addGroup(modificarEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarEliminarScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarEliminarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eliminarButton)))
                .addContainerGap())
        );
        modificarEliminarPanelLayout.setVerticalGroup(
            modificarEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarEliminarPanelLayout.createSequentialGroup()
                .addComponent(modificarEliminarScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregarTipoServicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modificarEliminarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarTipoServicioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarEliminarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarModificarButton;
    private javax.swing.JPanel agregarTipoServicioPanel;
    public javax.swing.JButton eliminarButton;
    public javax.swing.JList modificarEliminarList;
    private javax.swing.JPanel modificarEliminarPanel;
    private javax.swing.JScrollPane modificarEliminarScrollPane;
    private javax.swing.JLabel tipoServicioLabel;
    public javax.swing.JTextField tipoServicioTextField;
    // End of variables declaration//GEN-END:variables
}
